export const GET_ALL_CHARACTERS_BEGIN = "GET_ALL_CHARACTERS_BEGIN";
export const GET_ALL_CHARACTERS_SUCCESS = "GET_ALL_CHARACTERS_SUCCESS";
export const GET_ALL_CHARACTERS_FAIL = "GET_ALL_CHARACTERS_FAIL";

export const GET_CHARACTER_BEGIN = "GET_CHARACTER_BEGIN";
export const GET_CHARACTER_SUCCESS = "GET_CHARACTER_SUCCESS";
export const GET_CHARACTER_FAIL = "GET_CHARACTER_FAIL";

export const SET_SELECTED_CHARACTER = "SET_SELECTED_CHARACTER";
export const RESET_SELECTED_CHARACTER = "RESET_SELECTED_CHARACTER";
